apiVersion: v1
kind: Service
metadata:
  name: nblaunch
  labels:
    app.kubernetes.io/name: nblaunch
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nblaunch
  ports:
    - name: http
      port: 8000
      targetPort: http
